Format shell scripts with shfmt

diff --git a/bin/require b/bin/require
--- a/bin/require
+++ b/bin/require
@@ -9,11 +9,13 @@ set -euo pipefail
 IFS=$'\n\t'
 
 if [ $# -eq 0 ]; then
-    usage "$0"; exit 64
+    usage "$0"
+    exit 64
 fi
 
 for cmd; do
     if ! which -s "$cmd" >/dev/null; then
-        echo "${cmd}: command not found" >&2; exit 69
+        echo "${cmd}: command not found" >&2
+        exit 69
     fi
 done
